# File: models.py
from pydantic import BaseModel, Field, constr

# --- Custom Exceptions for Internal Handling ---
class ChronosException(Exception):
    """Base exception for Chronos service failures."""
    pass

class LLMSynthesisFailure(ChronosException):
    """Raised if the LLM API call or structured parsing fails."""
    pass

# --- Input Model (FastAPI Request Body) ---
class FragmentInput(BaseModel):
    """
    Input schema for the fragmented text artifact.
    """
    fragment_text: constr(min_length=10, max_length=1000) = Field(
        ...,
        description="The incomplete or cryptic text fragment for reconstruction."
    )

# --- Final Output Model (FastAPI Response Model) ---
class ReconstructionReport(BaseModel):
    """
    The final structured report returned to the frontend.
    """
    # Populated by the orchestration layer *after* Gemini runs
    original_fragment: str = Field(..., description="The initial, original text fragment provided by the user.")

    # Generated directly by the Gemini model
    reconstructed_text: str = Field(
        ...,
        description="The complete, contextually plausible text generated by Gemini."
    )
    plausibility_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="LLM's certainty score (0.0 to 1.0) for the reconstruction."
    )
    justification_summary: str = Field(
        ...,
        description="Detailed explanation of the reasoning and evidence-based decisions (CoT output)."
    )