# File: models.py
from pydantic import BaseModel, Field, constr
from typing import List, Optional

# --- Custom Exceptions for Internal Handling ---
class ChronosException(Exception):
    """Base exception for Chronos service failures."""
    pass

class GroundingFailure(ChronosException):
    """Raised if the external CSE service fails."""
    pass

class LLMSynthesisFailure(ChronosException):
    """Raised if the LLM API call or structured parsing fails."""
    pass

# --- Input Model (FastAPI Request Body) ---
class FragmentInput(BaseModel):
    """
    Input schema for the fragmented text artifact.
    """
    fragment_text: constr(min_length=10, max_length=1000) = Field(
   ...,
        description="The incomplete or cryptic text fragment for reconstruction."
    )

# --- Nested Source Model for the Final Report ---
class SourceModel(BaseModel):
    """
    Structure for returned grounding source metadata (the Contextual Sources list).
    """
    title: str = Field(..., description="Title of the source document.")
    uri: str = Field(..., description="Full URL to the source.")
    snippet: str = Field(..., description="The specific text snippet used as context.")

# --- Final Output Model (FastAPI Response Model) ---
class ReconstructionReport(BaseModel):
    """
    The final structured report returned to the frontend.
    """
    # Populated by the orchestration layer *after* Gemini runs
    original_fragment: str = Field(..., description="The initial, original text fragment provided by the user.")
    contextual_sources: List = Field(..., description="List of web sources used to ground the final reconstruction.")

    # Generated directly by the Gemini model
    reconstructed_text: str = Field(
    ..., 
        description="The complete, contextually plausible text generated by Gemini."
    )
    plausibility_score: float = Field(
    ..., 
        ge=0.0, 
        le=1.0, 
        description="LLM's certainty score (0.0 to 1.0) for the reconstruction."
    )
    justification_summary: str = Field(
    ..., 
        description="Detailed explanation of the reasoning and evidence-based decisions (CoT output)."
    )