# File: services/chronos_service.py
import asyncio

from google import genai
from google.genai import types
from google.genai.errors import APIError as GeminiAPIError
from models import ReconstructionReport, SourceModel, LLMSynthesisFailure, GroundingFailure
from config import Settings
from services.keyword_extractor import KeywordExtractor
from services.grounding_service import GroundingService
from typing import List

class ChronosService:
    """
    The orchestrator for Project Chronos. Executes the full single-call RAG pipeline.
    """
    
    LLM_TEMPERATURE = 0.1 
    LLM_MODEL = "gemini-2.5-flash" 
    
    SYSTEM_INSTRUCTIONS = (
        "You are Project Chronos, an expert Digital Archeologist and synthesis engine. "
        "Your task is to reconstruct the fragmented text provided in <FRAGMENT_INPUT>. "
        "Your reconstruction MUST be based ONLY on the contextual evidence provided "
        "in the CONTEXT section. Do not use external knowledge or speculation. "
        "If the CONTEXT section explicitly states 'NO_CONTEXT_AVAILABLE', you MUST "
        "reply only with the statement: 'I cannot provide a grounded reconstruction "
        "because the required external context was unavailable.' "
        "The response must be a single JSON object adhering strictly to the provided "
        "Pydantic schema (ReconstructionReport)."
    )
    
    def __init__(self, settings: Settings, extractor: KeywordExtractor, grounding_service: GroundingService):
        self.settings = settings
        self.extractor = extractor
        self.grounding_service = grounding_service
        
        # Initialize Gemini client securely using SecretStr value
        self.llm_client = genai.Client(
            api_key=settings.GEMINI_API_KEY.get_secret_value()
        )

    async def _construct_prompt(self, original_fragment: str, context_string: str) -> str:
        """Assembles the composite RAG prompt using clear delimiters."""
        return f"""
{self.SYSTEM_INSTRUCTIONS}

---

{context_string}

---

<FRAGMENT_INPUT>
{original_fragment}
</FRAGMENT_INPUT>

---

<TASK_GOAL>
Perform the linguistic and contextual reconstruction. Use Chain-of-Thought (CoT) to generate a detailed 'justification_summary' explaining how the evidence supports the reconstruction. Assign a 'plausibility_score' from 0.0 to 1.0. Output the final result as a single JSON object matching the required schema.
</TASK_GOAL>
"""

    async def process_query(self, user_query: str) -> ReconstructionReport:
        """
        Executes the full, single-call RAG pipeline.
        """
        
        # 1. Local Keyword Extraction (Fast, Non-LLM)
        extracted_keywords = self.extractor.extract_keywords(user_query)
        
        # 2. Asynchronous Grounding Retrieval (I/O)
        grounding_sources: List
        context_string: str
        try:
            grounding_sources, context_string = await self.grounding_service.get_grounding_context(extracted_keywords)
        except GroundingFailure:
             raise 

        # 3. Prompt Construction and Single LLM Synthesis (The only Gemini call)
        full_prompt = await self._construct_prompt(user_query, context_string)
        
        try:
            # Enforce structured output and low temperature. The google-genai 1.x Client
            # exposes only synchronous helpers, so we offload to a worker thread to avoid
            # blocking the event loop.
            response = await asyncio.to_thread(
                self.llm_client.models.generate_content,
                model=self.LLM_MODEL,
                contents=full_prompt,
                config=types.GenerateContentConfig(
                    temperature=self.LLM_TEMPERATURE,
                    response_mime_type="application/json",
                    response_schema=ReconstructionReport,
                ),
            )
            
            # The SDK automatically parses the JSON text into the Pydantic object
            report: ReconstructionReport = response.parsed
            
        except GeminiAPIError as e:
            raise LLMSynthesisFailure(f"Gemini API error during synthesis: {str(e)}") from e
        except Exception as e:
            raise LLMSynthesisFailure(f"LLM synthesis or JSON parsing error: {str(e)}") from e
        
        # 4. Final Data Assembly (Populate metadata not generated by the LLM)
        report.original_fragment = user_query
        report.contextual_sources = grounding_sources
        
        return report