# File: services/chronos_service.py
import asyncio

from google import genai
from google.genai import types
from google.genai.errors import APIError as GeminiAPIError
from models import ReconstructionReport, LLMSynthesisFailure
from config import Settings

class ChronosService:
    """
    The orchestrator for Project Chronos. Executes the Gemini-only reconstruction flow.
    """
    
    LLM_TEMPERATURE = 0.1 
    LLM_MODEL = "gemini-2.5-flash" 
    
    SYSTEM_INSTRUCTIONS = (
        "You are Project Chronos, an expert Digital Archeologist and synthesis engine. "
        "Your task is to reconstruct the fragmented text provided in <FRAGMENT_INPUT>. "
        "Draw solely on your internal knowledge and reasoning—no external lookups are available. "
        "Return the result as JSON that conforms exactly to the ReconstructionReport schema."
    )
    
    def __init__(self, settings: Settings):
        self.settings = settings
        
        # Initialize Gemini client securely using SecretStr value
        self.llm_client = genai.Client(
            api_key=settings.GEMINI_API_KEY.get_secret_value()
        )

    async def _construct_prompt(self, original_fragment: str) -> str:
        """Assembles the Gemini prompt."""
        return f"""
{self.SYSTEM_INSTRUCTIONS}

---
<FRAGMENT_INPUT>
{original_fragment}
</FRAGMENT_INPUT>

---

<TASK_GOAL>
Perform the linguistic and contextual reconstruction. Use Chain-of-Thought (CoT) to generate a detailed 'justification_summary' explaining your reasoning. Assign a 'plausibility_score' from 0.0 to 1.0. Output the final result as a single JSON object matching the required schema.
</TASK_GOAL>
"""

    async def process_query(self, user_query: str) -> ReconstructionReport:
        """
        Executes the single-call Gemini pipeline without external grounding.
        """

        # Single LLM prompt and synthesis
        full_prompt = await self._construct_prompt(user_query)
        
        try:
            # Enforce structured output and low temperature. The google-genai 1.x Client
            # exposes only synchronous helpers, so we offload to a worker thread to avoid
            # blocking the event loop.
            response = await asyncio.to_thread(
                self.llm_client.models.generate_content,
                model=self.LLM_MODEL,
                contents=full_prompt,
                config=types.GenerateContentConfig(
                    temperature=self.LLM_TEMPERATURE,
                    response_mime_type="application/json",
                    response_schema=ReconstructionReport,
                ),
            )
            
            # The SDK automatically parses the JSON text into the Pydantic object
            report: ReconstructionReport = response.parsed
            
        except GeminiAPIError as e:
            raise LLMSynthesisFailure(f"Gemini API error during synthesis: {str(e)}") from e
        except Exception as e:
            raise LLMSynthesisFailure(f"LLM synthesis or JSON parsing error: {str(e)}") from e

        # Populate metadata not generated by the LLM
        report.original_fragment = user_query
        
        return report